/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_resp/src/sql.rs:343
CREATE SCHEMA IF NOT EXISTS resp; /* pg_resp::sql::resp */
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_resp/src/sql.rs:360
-- pg_resp::sql::resp::exists
CREATE  FUNCTION resp."exists"(
	"key" TEXT /* & str */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'exists_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_resp/src/sql.rs:388
-- pg_resp::sql::resp::keys
CREATE  FUNCTION resp."keys"(
	"pattern" TEXT /* & str */
) RETURNS SETOF TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'keys_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_resp/src/sql.rs:352
-- pg_resp::sql::resp::get
CREATE  FUNCTION resp."get"(
	"key" TEXT /* & str */
) RETURNS TEXT /* Option < String > */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_resp/src/sql.rs:412
-- pg_resp::sql::resp::set
CREATE  FUNCTION resp."set"(
	"key" TEXT, /* & str */
	"value" TEXT, /* & str */
	"ttl_seconds" bigint DEFAULT NULL /* Option < i64 > */
) RETURNS void
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'set_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_resp/src/sql.rs:373
-- pg_resp::sql::resp::ttl
CREATE  FUNCTION resp."ttl"(
	"key" TEXT /* & str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ttl_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_resp/src/sql.rs:431
-- pg_resp::sql::resp::del
CREATE  FUNCTION resp."del"(
	"key" TEXT /* & str */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'del_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_resp/src/sql.rs:447
-- pg_resp::sql::resp::stats
CREATE  FUNCTION resp."stats"() RETURNS TABLE (
	"keys" bigint,  /* i64 */
	"used_bytes" bigint,  /* i64 */
	"max_memory_bytes" bigint,  /* i64 */
	"keyspace_hits" bigint,  /* i64 */
	"keyspace_misses" bigint,  /* i64 */
	"evicted_keys" bigint,  /* i64 */
	"invalidations_lost" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_resp/src/sql.rs:492
-- pg_resp::sql::resp::evict
CREATE FUNCTION resp."evict"()
	RETURNS TRIGGER
	LANGUAGE c
	AS 'MODULE_PATHNAME', 'evict_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- crates/pg_resp/src/sql.rs:654
-- finalize

REVOKE ALL ON SCHEMA resp FROM PUBLIC;
REVOKE ALL ON FUNCTION resp.get(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION resp.exists(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION resp.ttl(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION resp.keys(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION resp.set(text, text, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION resp.del(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION resp.stats() FROM PUBLIC;
REVOKE ALL ON FUNCTION resp.evict() FROM PUBLIC;
/* </end connected objects> */

